[package]
name = "orbity-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "orbity"
path = "src/main.rs"

[dependencies]
orbity-core.workspace = true
orbity-storage.workspace = true
orbity-sandbox.workspace = true
orbity-graph.workspace = true
orbity-agent.workspace = true
orbity-telemetry.workspace = true
orbity-server.workspace = true
clap.workspace = true
tokio.workspace = true
sqlx.workspace = true
uuid.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
thiserror.workspace = true

tracing.workspace = true
tracing-subscriber.workspace = true

