[package]
name = "orbity-graph"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
orbity-core.workspace = true
orbity-storage.workspace = true
sqlx.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
chrono.workspace = true
sha2.workspace = true
hex.workspace = true
thiserror.workspace = true
uuid.workspace = true
tokio.workspace = true
async-trait.workspace = true
tracing.workspace = true


